[package]
name = "oskar"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
authors = ["Jonas Loeffelholz <jonas.loeffelholz@9elements.com>"]

[dependencies]
assign-resources = "0.4.1"
cortex-m = { version = "0.7.7", features = ["inline-asm", "critical-section"] }
cortex-m-rt = "0.7.5"
critical-section = "1.2.0"
defmt = "0.3.10"
defmt-rtt = "0.4.1"
embassy-executor = { version = "0.7.0", features = ["arch-cortex-m", "executor-thread", "executor-interrupt", "nightly"] }
embassy-futures = "0.1.1"
embassy-rp = { version = "0.3.0", features = ["unstable-pac", "time-driver", "critical-section-impl", "rom-func-cache", "rom-v2-intrinsics", "rp2040"] }
embassy-sync = "0.6.2"
embassy-time = "0.4.0"
embassy-usb = { version = "0.4.0", features = ["max-handler-count-6", "max-interface-count-6"] }
embedded-hal = "1.0.0"
embedded-hal-async = "1.0.0"
futures = { version = "0.3.31", default-features = false, features = ["async-await", "cfg-target-has-atomic", "unstable"] }
heapless = { version = "0.8.0", features = ["portable-atomic-critical-section", "ufmt"] }
log = "0.4.26"
panic-probe = { version = "0.3.2", features = ["print-defmt"] }
portable-atomic = { version = "1.11.0", features = ["critical-section"] }
serprog = { git = "https://github.com/9elements/picoprog" }
static_cell = "2.1.0"
tock-registers = "0.9.0"
ufmt = "0.2.0"
zerocopy = { version = "0.8", features = ["derive"] }
num_enum = { version = "0.7.3", default-features = false }
smart-leds = "0.4.0"

[patch.crates-io]
embassy-executor = { git = "https://github.com/embassy-rs/embassy", rev = "17301c00e986c5b8536435ea31ebf5aaf13aed17" }
embassy-futures = { git = "https://github.com/embassy-rs/embassy", rev = "17301c00e986c5b8536435ea31ebf5aaf13aed17" }
embassy-rp = { git = "https://github.com/embassy-rs/embassy", rev = "17301c00e986c5b8536435ea31ebf5aaf13aed17" }
embassy-sync = { git = "https://github.com/embassy-rs/embassy", rev = "17301c00e986c5b8536435ea31ebf5aaf13aed17" }
embassy-time = { git = "https://github.com/embassy-rs/embassy", rev = "17301c00e986c5b8536435ea31ebf5aaf13aed17" }
embassy-usb = { git = "https://github.com/embassy-rs/embassy", rev = "17301c00e986c5b8536435ea31ebf5aaf13aed17" }

[profile.release]
debug = true
incremental = false
codegen-units = 1
opt-level = 0
lto = "fat"
